# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget tesseract::tesseract_motion_planners_core tesseract::tesseract_motion_planners_simple tesseract::tesseract_motion_planners_ompl tesseract::tesseract_motion_planners_descartes tesseract::tesseract_motion_planners_trajopt tesseract::tesseract_motion_planners_trajopt_ifopt)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target tesseract::tesseract_motion_planners_core
add_library(tesseract::tesseract_motion_planners_core SHARED IMPORTED)

set_target_properties(tesseract::tesseract_motion_planners_core PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_COMPILE_OPTIONS "-mno-avx"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "tesseract::tesseract_environment;tesseract::tesseract_common;tesseract::tesseract_command_language;console_bridge::console_bridge;Eigen3::Eigen"
)

# Create imported target tesseract::tesseract_motion_planners_simple
add_library(tesseract::tesseract_motion_planners_simple SHARED IMPORTED)

set_target_properties(tesseract::tesseract_motion_planners_simple PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_COMPILE_OPTIONS "-mno-avx"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "tesseract::tesseract_motion_planners_core;Boost::boost"
)

# Create imported target tesseract::tesseract_motion_planners_ompl
add_library(tesseract::tesseract_motion_planners_ompl SHARED IMPORTED)

set_target_properties(tesseract::tesseract_motion_planners_ompl PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_COMPILE_OPTIONS "-mno-avx"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;/opt/ros/humble/include/ompl-1.6;/usr/include;/usr/include/eigen3"
  INTERFACE_LINK_LIBRARIES "tesseract::tesseract_motion_planners_core;/opt/ros/humble/lib/x86_64-linux-gnu/libompl.so;/usr/lib/x86_64-linux-gnu/libboost_serialization.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;ode;Boost::boost"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "/opt/ros/humble/include/ompl-1.6;/usr/include;/usr/include/eigen3"
)

# Create imported target tesseract::tesseract_motion_planners_descartes
add_library(tesseract::tesseract_motion_planners_descartes SHARED IMPORTED)

set_target_properties(tesseract::tesseract_motion_planners_descartes PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_COMPILE_OPTIONS "-mno-avx"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "tesseract::tesseract_motion_planners_core;tesseract::tesseract_collision_core;descartes::descartes_light;Boost::boost"
)

# Create imported target tesseract::tesseract_motion_planners_trajopt
add_library(tesseract::tesseract_motion_planners_trajopt SHARED IMPORTED)

set_target_properties(tesseract::tesseract_motion_planners_trajopt PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_COMPILE_OPTIONS "-mno-avx"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "tesseract::tesseract_motion_planners_core;trajopt::trajopt;trajopt::trajopt_common;trajopt::trajopt_sco;Boost::boost;Eigen3::Eigen"
)

# Create imported target tesseract::tesseract_motion_planners_trajopt_ifopt
add_library(tesseract::tesseract_motion_planners_trajopt_ifopt SHARED IMPORTED)

set_target_properties(tesseract::tesseract_motion_planners_trajopt_ifopt PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_COMPILE_OPTIONS "-mno-avx"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "tesseract::tesseract_motion_planners_core;trajopt::trajopt_ifopt;trajopt::trajopt_sqp;Boost::boost;Eigen3::Eigen"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/tesseract_motion_planners-targets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
